//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncServiceDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContributionSet
    {
        public int ContributionId { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public string Type { get; set; }
        public int EventEventId { get; set; }
        public int PersonPersonId { get; set; }
    
        public virtual EventSet EventSet { get; set; }
        public virtual PersonSet PersonSet { get; set; }
    }
}
