//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncServiceDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSet
    {
        public EventSet()
        {
            this.ContributionSets = new HashSet<ContributionSet>();
            this.PersonSets = new HashSet<PersonSet>();
        }
    
        public int EventId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public string Type { get; set; }
        public int PersonPersonId { get; set; }
        public int Adress_AdressId { get; set; }
    
        public virtual AdressSet AdressSet { get; set; }
        public virtual ICollection<ContributionSet> ContributionSets { get; set; }
        public virtual ICollection<PersonSet> PersonSets { get; set; }
    }
}
